from PyQt5 import QtCore, QtWidgets


class Ui_RJM(object):
    def setupUi(self, RJM):
        RJM.setObjectName("RJM")
        RJM.resize(781, 278)
        self.formLayoutWidget = QtWidgets.QWidget(RJM)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 262))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_openfile = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_openfile.setObjectName("pushButton_openfile")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_openfile)
        self.label_name_file = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_name_file.setObjectName("label_name_file")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_name_file)
        self.label_tag_text = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_tag_text.setObjectName("label_tag_text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_tag_text)
        self.label_tag = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_tag.setObjectName("label_tag")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_tag)
        self.label_original = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_original.setObjectName("label_original")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_original)
        self.lineEdit_original = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_original.setObjectName("lineEdit_original")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_original)
        self.line_3 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.line_3)
        self.line_2 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_2)
        self.label_translate_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_translate_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_translate_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_translate_2.setObjectName("label_translate_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_translate_2)
        self.lineEdit_translate = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_translate.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.lineEdit_translate.setObjectName("lineEdit_translate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_translate)
        self.line = QtWidgets.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line)
        self.label_translate = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_translate.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_translate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_translate.setObjectName("label_translate")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_translate)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.line_4 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.line_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.push_skip = QtWidgets.QPushButton(self.formLayoutWidget)
        self.push_skip.setObjectName("push_skip")
        self.gridLayout.addWidget(self.push_skip, 1, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 1, 1, 1)
        self.pushButton_save_file = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_save_file.setObjectName("pushButton_save_file")
        self.gridLayout.addWidget(self.pushButton_save_file, 2, 1, 1, 1)
        self.pushButton_next = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout.addWidget(self.pushButton_next, 1, 2, 1, 1)
        self.pushButton_backup = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_backup.setObjectName("pushButton_backup")
        self.gridLayout.addWidget(self.pushButton_backup, 2, 0, 1, 1)
        self.pushButton_AllTranslate = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_AllTranslate.setObjectName("pushButton_AllTranslate")
        self.gridLayout.addWidget(self.pushButton_AllTranslate, 2, 2, 1, 1)
        self.formLayout.setLayout(9, QtWidgets.QFormLayout.SpanningRole, self.gridLayout)

        self.retranslateUi(RJM)
        QtCore.QMetaObject.connectSlotsByName(RJM)

    def retranslateUi(self, RJM):
        _translate = QtCore.QCoreApplication.translate
        RJM.setWindowTitle(_translate("RJM", "Dialog"))
        self.pushButton_openfile.setText(_translate("RJM", "Открыть файл"))
        self.label_name_file.setText(_translate("RJM", "--none--"))
        self.label_tag_text.setText(_translate("RJM", "Tag and num string:"))
        self.label_tag.setText(_translate("RJM", "--none--"))
        self.label_original.setText(_translate("RJM", "Original string:"))
        self.label_translate_2.setText(_translate("RJM", "Google Translate:"))
        self.label_translate.setText(_translate("RJM", "Final:"))
        self.push_skip.setText(_translate("RJM", "< - Туда"))
        self.pushButton_save.setText(_translate("RJM", "Save string"))
        self.pushButton_save_file.setText(_translate("RJM", "Save full file"))
        self.pushButton_next.setText(_translate("RJM", "Сюда - >"))
        self.pushButton_backup.setText(_translate("RJM", "Backup"))
        self.pushButton_AllTranslate.setText(_translate("RJM", "All Translate"))

